### ISSUE TITLE
Unit tests not found in subfolders under web/modules

### ISSUE THREAD

**Issue by kasperg** [drupal-composer/drupal-composer-project#123]
drupal-project is designed to have contrib modules placed in `web/modules/contrib`. Tests in subfolderers under `web/modules` are not found due to the configuration in [the current `phpunit.xml.dist`](http://cgit.drupalcode.org/drupal/tree/core/phpunit.xml.dist).

This becomes more problematic if follow a similar pattern and also place custom modules in `web/modules/custom`.

There is [an issue for this on drupal.org](https://www.drupal.org/node/2499239) and [a patch that works for me](https://www.drupal.org/node/2499239#comment-10810964).

I do not know whether this should result in drupal-project patching `drupal/core` by default if other people run into this problem this info might be helpful.

**Comment by webflo** [comment]
The core issue has been fixed. I think we can close the issue. Please comment if you disagree.

**Comment by amitaibu** [comment]
@webflo I was still unable to execute my tests. What's the command you run to execute your custom modules tests?

**Comment by webflo** [comment]
@amitaibu See my comment on the other issue.

**Comment by weitzman** [comment]
From one of my projects:

`SIMPLETEST_BASE_URL=http://foo.amazee.io
SIMPLETEST_DB=mysql://drupal:drupal@localhost/drupal#simpletest
$HOME/public_html/vendor/bin/phpunit -c $WEBROOT/core --verbose
$HOME/public_html/$WEBROOT/profiles/example/modules/custom/`

The last directory tells phpunit where to start looking for tests.
